//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BangGameLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BangGameLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;DistanceFromOthers&quot;: 0,
        ///    &quot;SeeingDistance&quot;: 1,
        ///    &quot;SeeingAttackDistance&quot;: 0,
        ///    &quot;Hero&quot;: &quot;BartCassidy&quot;,
        ///    &quot;MaxHealth&quot;: 4
        ///  },
        ///  {
        ///    &quot;DistanceFromOthers&quot;: 0,
        ///    &quot;SeeingDistance&quot;: 1,
        ///    &quot;SeeingAttackDistance&quot;: 0,
        ///    &quot;Hero&quot;: &quot;BlackJack&quot;,
        ///    &quot;MaxHealth&quot;: 4
        ///  },
        ///  {
        ///    &quot;DistanceFromOthers&quot;: 0,
        ///    &quot;SeeingDistance&quot;: 1,
        ///    &quot;SeeingAttackDistance&quot;: 0,
        ///    &quot;Hero&quot;: &quot;CalamityJanet&quot;,
        ///    &quot;MaxHealth&quot;: 4
        ///  },
        ///  {
        ///    &quot;DistanceFromOthers&quot;: 0,
        ///    &quot;SeeingDistance&quot;: 1,
        ///    &quot;Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HeroCards {
            get {
                return ResourceManager.GetString("HeroCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Num&quot;: &quot;2&quot;,
        ///    &quot;Color&quot;: &quot;heart&quot;,
        ///    &quot;Type&quot;: &quot;Dynamite&quot;
        ///  },
        ///  {
        ///    &quot;Num&quot;: &quot;Q&quot;,
        ///    &quot;Color&quot;: &quot;spade&quot;,
        ///    &quot;Type&quot;: &quot;Barel&quot;
        ///  },
        ///  {
        ///    &quot;Num&quot;: &quot;K&quot;,
        ///    &quot;Color&quot;: &quot;spade&quot;,
        ///    &quot;Type&quot;: &quot;Barel&quot;
        ///  },
        ///  {
        ///    &quot;Num&quot;: &quot;A&quot;,
        ///    &quot;Color&quot;: &quot;spade&quot;,
        ///    &quot;Type&quot;: &quot;Mirino&quot;
        ///  },
        ///  {
        ///    &quot;Num&quot;: &quot;8&quot;,
        ///    &quot;Color&quot;: &quot;heart&quot;,
        ///    &quot;Type&quot;: &quot;Mustang&quot;
        ///  },
        ///  {
        ///    &quot;Num&quot;: &quot;9&quot;,
        ///    &quot;Color&quot;: &quot;heart&quot;,
        ///    &quot;Type&quot;: &quot;Mustang&quot;
        ///  },
        ///  {
        ///    &quot;Num&quot;: &quot;J&quot;,
        ///    &quot;Color&quot;: &quot;spade&quot;,
        ///    &quot;Type&quot;: &quot;Prison&quot;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayingCards {
            get {
                return ResourceManager.GetString("PlayingCards", resourceCulture);
            }
        }
    }
}
